strangerstudios/pmpro-woocommerce

- pmpro-woocommerce.php
Didn't process the membership cancellation since the woocommerce_order_status_cancelled action wasn't hooked.
> BUG: Didn't trigger cancellation of membership

- email/gift_membership_code.html
- pmpro-woocommerce.php
This new addition allows for a better Gift Membership experience through WooCommerce.
- Ability to select existing PMPro Discount Code to sell
- Unique 1-time-use copy of Discount Code created at purchase
- Ability to email new Member Gift Code to a Recipient or to Customer
- New Email Template created: gift_membership_code.html
- New Email Tag: !!gift_product!!  =>  Title of the Product
- New Email Tag: !!membership_gift_code!!  => Generated Gift Code
I know others wanted this functionality so hope it helps the community :)
> Addon: Sell PmPro Discount Codes through WooCommerce

- pmpro-woocommerce.php
Deactivating the "Autocomplete order" checkbox for "Memberships" didn't save the new state (unchecked)
> BUG FIX: Deactivating 'autocomplete' didn't work

- pmpro-woocommerce.php
- readme.txt
Fix typo woocommerce_order_status_on-hold
Update tested up to version
> Fix typo woocommerce_order_status_on-hold

- pmpro-woocommerce.php
To replicate issue:
1. Set "Decimal separator" in WooCommerce to be `,` or any character besides `.`
2. Add a membership price to a product that is not a whole number (ie. `15,95`)
3. Save product
4. View product page on site frontend
5. See that the decimal part of number is left off (would show `15,00`)
This is because we were saving the price in the database with the custom decimal separator, whereas WooCommerce always saves prices in the database with `.` as the decimal separator, regardless of the custom separator set. This change makes our Membership Prices save more similarly to WC prices.
> Membership prices now handle different decimal separators

- pmpro-woocommerce.php
How to replicate the issue: 
- Create a variable product
- Set the Member discount to the product to $0
- Add a variation to your cart
- Discount won't be applied
This is because we use the product ID and that then references the variable item instead of the parent. 
This PR then uses the parent ID instead because we save the discount values to the ID. 
Long term we should maybe consider adding support for discounts for each variation too.
> Discounts apply to the variation product and not the parent

- includes/functions.php
WC subscription orders in `pending-cancel` status are still active subscriptions, though they will be fully cancelled at the end of the current payment period. As such, PMPro users should keep their membership level if their subscription is in `pending-cancel` status.
Original ticket (demonstrates strange behavior that can occur without this fix): https://www.paidmembershipspro.com/forums/topic/problem-with-membership-reset/
> pmprowoo_user_has_active_membership_product_for_level() now looks for pending-cancel status

- pmpro-woocommerce.php
Related to #134 
We now check if there's a value present and if not, set it to 0.
> Checks for an empty value before calculating discount

- pmpro-woocommerce.php
Relates to #136 
We now extend a level if there's an expiration date present. 
We also take into account hourly expirations and can calculate if they should be extended too.
> Expiration dates tidied up. Hourly expirations accounted for.

- pmpro-woocommerce.php
Previously, the membership would be extended both when calculating `$total_days` with `$days_left`, and again with passing `$expiration_date` as a second parameter to `strtotime()`.
This PR removes this double-adjustment by removing the `$total_days` logic, which also ends up simplifying the function.
> Fixed issue where membeship would be double extended.

- includes/pmpro-gift-levels.php
Gift Recipient Name & Email were not saving in the newer version of WooCommerce.  Changed the woocommerce_new_order_item action hook
> FIX:  Gift Recipient Name & Email not saving in newer WooCommerce

- pmpro-woocommerce.php
Use of $has_sub is not defined anywhere in the function. Might have been a copy/paste error while moving the function into an if statement. 
Resolves #170 
Steps to recreate: 
1. Enable debug loggins
2. Ensure that the user has a membership level that is associated with a subscription in Woo
3. Cancel the subscription
4. No error should be reported anymore
> Removed an undefined variable

- pmpro-woocommerce.php
Products that are set to autocomplete an order would fail when purchasing a variable product. This PR ensures that the order will autocomplete as expected. 
Resolves #108 
Steps on how to test: 
1. Create a variable product.
2. Assign the level and set it to autocomplete the order on the Membership Settings
3. Purchase the product
4. The order should autocomplete and the membership level be assigned as expected.
> Autocompletes order for Variable Products

- pmpro-woocommerce.php
The new solution will find the largest discount possible based on the user's current membership levels and all membership products in their cart (besides for the product that we are calculating a price for).
> Adding MMPU compatibility for discounting products

- pmpro-woocommerce.php
$_product can be false. This is because the ->get_product() has these return types: \WC_Product|false. Then we should check if $_product instanceof \WC_Product or continue;
Cases:
- Order with an empty line
- Plugins which permit to buy (in WC cart) items (CPT) which are NOT extending the \WC_Product class.
- Order with a raw line_item
> Avoid fatal error: Uncaught Error: Call to a member function get_id() on bool

- pmpro-woocommerce.php
* BUG FIX: Fix an issue where autocomplete checkbox wasn't saving. This was due to escaping the checkbox value (and woocommerce function was escaping it as well).
Added exclusion to PHPCS for escaping output warnings as values are already escaped. Moved up saving the the $autocomplete value when saving the product meta to make code easier to follow.
> Removed escaping as it was already escaped

- pmpro-woocommerce.php
* BUG FIX: Stop WooCommerce Subscription renewal orders from restarting the members level for each order.
Resolves [#188](https://github.com/strangerstudios/pmpro-woocommerce/issues/188).
1. Create a WooCommerce Subscription Product tied to a membership level. Buy it.
2. Navigate to WooCommerce > Status > Scheduled Actions and search for the subscription ID and run the scheduler to process the subscription.
3. A new WooCommerce order is created, be sure to mark it as completed and notice that the user's current level wouldn't change or reset in Member History section.
> Fix Woo Subs Renewal Restart

- pmpro-woocommerce.php
* BUG FIX: Fixed an issue where variation subscriptions were being discounted incorrectly.
Resolves: https://github.com/strangerstudios/pmpro-woocommerce/issues/187
> FIX: Discounting incorrectly for variation subscriptions

- pmpro-woocommerce.php
* ENHANCEMENT: Show a different message when the item in the cart is for the level you are looking at.
This shows a different message when viewing a membership linked product that is already in your cart, to make things clearer. It doesn't compare levels linked to the product itself but as long as it's a level linked product we show a different message.
Resolves: https://github.com/strangerstudios/pmpro-woocommerce/issues/81
> Show a different message for viewing same product that's in the cart

- includes/functions.php
* BUG FIX: Fixed an issue where cancelling a variable subscription wouldn't remove the membership level from the user.
This will remove the level upon cancelling immediately.
Resolves XXX.
1. Create a variation subscription with 2 or more variations.
2. Set this product to assign a membership level ID when purchased.
3. Checkout for this product, if the order doesn't autocomplete or you're on local be sure to mark the order as successful/completed.
4. Cancel your subscription for this product
5. See that the customer's membership level was removed.
> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.
> Fix cancellations not working on Variable Subscriptions

- pmpro-woocommerce.php
* ENHANCEMENT: Added functionality to detect if level groups allow single or multiple levels and make the products available for checkout within a single cart.
For example if level 1 is in group 1 and group 1 only allows one level per group you may only add one to your cart per checkout. If you have a level that belongs to a group with multiple levels, you may add as many products as you'd like within this group.
> Added PMPro v3.0 compatibility.

- pmpro-woocommerce.php
Throughout a WC checkout flow, the `woocommerce_is_purchasable` filter is used to determine whether each product in a cart can be purchased. For PMPro level groups that only allow users to have one level for the group, we use that filter to ensure that the user is not trying to purchase multiple levels from that group at once.
Before this PR, there was an issue that whenever a level from  "single level group" was in the cart, it would check if there are any other levels in the cart, see itself, and say "oops, we can't purchase this!"
This PR updates the logic so that products ignore themselves while checking if other levels from the same group are being purchased.
Resolves XXX.
> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.
> Fix purchasing levels from single level group

- includes/pmpro-gift-levels.php
Two strings in pmpro-gift-levels.php can now be localized
Two strings in pmpro-gift-levels.php can now be localized
> Two strings in pmpro-gift-levels.php can now be localized
